'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class EditorLocalization
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.EditorLocalization", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bold.
        '''</summary>
        Friend Shared ReadOnly Property Bold() As String
            Get
                Return ResourceManager.GetString("Bold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert hyperlink.
        '''</summary>
        Friend Shared ReadOnly Property CreateLink() As String
            Get
                Return ResourceManager.GetString("CreateLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteFile() As String
            Get
                Return ResourceManager.GetString("DeleteFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A directory with this name was not found..
        '''</summary>
        Friend Shared ReadOnly Property DirectoryNotFound() As String
            Get
                Return ResourceManager.GetString("DirectoryNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Empty Folder.
        '''</summary>
        Friend Shared ReadOnly Property EmptyFolder() As String
            Get
                Return ResourceManager.GetString("EmptyFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select font family.
        '''</summary>
        Friend Shared ReadOnly Property FontName() As String
            Get
                Return ResourceManager.GetString("FontName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (inherited font).
        '''</summary>
        Friend Shared ReadOnly Property FontNameInherit() As String
            Get
                Return ResourceManager.GetString("FontNameInherit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select font size.
        '''</summary>
        Friend Shared ReadOnly Property FontSize() As String
            Get
                Return ResourceManager.GetString("FontSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (inherited size).
        '''</summary>
        Friend Shared ReadOnly Property FontSizeInherit() As String
            Get
                Return ResourceManager.GetString("FontSizeInherit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select block type.
        '''</summary>
        Friend Shared ReadOnly Property FormatBlock() As String
            Get
                Return ResourceManager.GetString("FormatBlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indent.
        '''</summary>
        Friend Shared ReadOnly Property Indent() As String
            Get
                Return ResourceManager.GetString("Indent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert HTML.
        '''</summary>
        Friend Shared ReadOnly Property InsertHtml() As String
            Get
                Return ResourceManager.GetString("InsertHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert image.
        '''</summary>
        Friend Shared ReadOnly Property InsertImage() As String
            Get
                Return ResourceManager.GetString("InsertImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert ordered list.
        '''</summary>
        Friend Shared ReadOnly Property InsertOrderedList() As String
            Get
                Return ResourceManager.GetString("InsertOrderedList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert unordered list.
        '''</summary>
        Friend Shared ReadOnly Property InsertUnorderedList() As String
            Get
                Return ResourceManager.GetString("InsertUnorderedList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected file \&quot;{0}\&quot; is not valid. Supported file types are {1}..
        '''</summary>
        Friend Shared ReadOnly Property InvalidFileType() As String
            Get
                Return ResourceManager.GetString("InvalidFileType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Italic.
        '''</summary>
        Friend Shared ReadOnly Property Italic() As String
            Get
                Return ResourceManager.GetString("Italic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Center text.
        '''</summary>
        Friend Shared ReadOnly Property JustifyCenter() As String
            Get
                Return ResourceManager.GetString("JustifyCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Justify.
        '''</summary>
        Friend Shared ReadOnly Property JustifyFull() As String
            Get
                Return ResourceManager.GetString("JustifyFull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Align text left.
        '''</summary>
        Friend Shared ReadOnly Property JustifyLeft() As String
            Get
                Return ResourceManager.GetString("JustifyLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Align text right.
        '''</summary>
        Friend Shared ReadOnly Property JustifyRight() As String
            Get
                Return ResourceManager.GetString("JustifyRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arrange by:.
        '''</summary>
        Friend Shared ReadOnly Property OrderBy() As String
            Get
                Return ResourceManager.GetString("OrderBy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property OrderByName() As String
            Get
                Return ResourceManager.GetString("OrderByName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Size.
        '''</summary>
        Friend Shared ReadOnly Property OrderBySize() As String
            Get
                Return ResourceManager.GetString("OrderBySize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Outdent.
        '''</summary>
        Friend Shared ReadOnly Property Outdent() As String
            Get
                Return ResourceManager.GetString("Outdent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;A file with name &quot;{0}&quot; already exists in the current directory. Do you want to overwrite it?.
        '''</summary>
        Friend Shared ReadOnly Property OverwriteFile() As String
            Get
                Return ResourceManager.GetString("OverwriteFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Strikethrough.
        '''</summary>
        Friend Shared ReadOnly Property Strikethrough() As String
            Get
                Return ResourceManager.GetString("Strikethrough", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Styles.
        '''</summary>
        Friend Shared ReadOnly Property Style() As String
            Get
                Return ResourceManager.GetString("Style", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Underline.
        '''</summary>
        Friend Shared ReadOnly Property Underline() As String
            Get
                Return ResourceManager.GetString("Underline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove hyperlink.
        '''</summary>
        Friend Shared ReadOnly Property Unlink() As String
            Get
                Return ResourceManager.GetString("Unlink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upload.
        '''</summary>
        Friend Shared ReadOnly Property UploadFile() As String
            Get
                Return ResourceManager.GetString("UploadFile", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
