'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GridLocalization
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.GridLocalization", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add new record.
        '''</summary>
        Friend Shared ReadOnly Property AddNew() As String
            Get
                Return ResourceManager.GetString("AddNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel changes.
        '''</summary>
        Friend Shared ReadOnly Property CancelChanges() As String
            Get
                Return ResourceManager.GetString("CancelChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property Delete() As String
            Get
                Return ResourceManager.GetString("Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete this record?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteConfirmation() As String
            Get
                Return ResourceManager.GetString("DeleteConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Displaying items {0} - {1} of {2}.
        '''</summary>
        Friend Shared ReadOnly Property DisplayingItems() As String
            Get
                Return ResourceManager.GetString("DisplayingItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property Edit() As String
            Get
                Return ResourceManager.GetString("Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter.
        '''</summary>
        Friend Shared ReadOnly Property Filter() As String
            Get
                Return ResourceManager.GetString("Filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to And.
        '''</summary>
        Friend Shared ReadOnly Property FilterAnd() As String
            Get
                Return ResourceManager.GetString("FilterAnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is false.
        '''</summary>
        Friend Shared ReadOnly Property FilterBoolIsFalse() As String
            Get
                Return ResourceManager.GetString("FilterBoolIsFalse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is true.
        '''</summary>
        Friend Shared ReadOnly Property FilterBoolIsTrue() As String
            Get
                Return ResourceManager.GetString("FilterBoolIsTrue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear Filter.
        '''</summary>
        Friend Shared ReadOnly Property FilterClear() As String
            Get
                Return ResourceManager.GetString("FilterClear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterDateEq() As String
            Get
                Return ResourceManager.GetString("FilterDateEq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is after or equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterDateGe() As String
            Get
                Return ResourceManager.GetString("FilterDateGe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is after.
        '''</summary>
        Friend Shared ReadOnly Property FilterDateGt() As String
            Get
                Return ResourceManager.GetString("FilterDateGt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is before or equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterDateLe() As String
            Get
                Return ResourceManager.GetString("FilterDateLe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is before.
        '''</summary>
        Friend Shared ReadOnly Property FilterDateLt() As String
            Get
                Return ResourceManager.GetString("FilterDateLt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is not equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterDateNe() As String
            Get
                Return ResourceManager.GetString("FilterDateNe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterEnumEq() As String
            Get
                Return ResourceManager.GetString("FilterEnumEq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is not equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterEnumNe() As String
            Get
                Return ResourceManager.GetString("FilterEnumNe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterForeignKeyEq() As String
            Get
                Return ResourceManager.GetString("FilterForeignKeyEq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is not equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterForeignKeyNe() As String
            Get
                Return ResourceManager.GetString("FilterForeignKeyNe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterNumberEq() As String
            Get
                Return ResourceManager.GetString("FilterNumberEq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is greater than or equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterNumberGe() As String
            Get
                Return ResourceManager.GetString("FilterNumberGe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is greater than.
        '''</summary>
        Friend Shared ReadOnly Property FilterNumberGt() As String
            Get
                Return ResourceManager.GetString("FilterNumberGt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is less than or equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterNumberLe() As String
            Get
                Return ResourceManager.GetString("FilterNumberLe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is less than.
        '''</summary>
        Friend Shared ReadOnly Property FilterNumberLt() As String
            Get
                Return ResourceManager.GetString("FilterNumberLt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is not equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterNumberNe() As String
            Get
                Return ResourceManager.GetString("FilterNumberNe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -Select value-.
        '''</summary>
        Friend Shared ReadOnly Property FilterSelectValue() As String
            Get
                Return ResourceManager.GetString("FilterSelectValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show rows with value that.
        '''</summary>
        Friend Shared ReadOnly Property FilterShowRows() As String
            Get
                Return ResourceManager.GetString("FilterShowRows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ends with.
        '''</summary>
        Friend Shared ReadOnly Property FilterStringEndsWith() As String
            Get
                Return ResourceManager.GetString("FilterStringEndsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterStringEq() As String
            Get
                Return ResourceManager.GetString("FilterStringEq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is not equal to.
        '''</summary>
        Friend Shared ReadOnly Property FilterStringNe() As String
            Get
                Return ResourceManager.GetString("FilterStringNe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starts with.
        '''</summary>
        Friend Shared ReadOnly Property FilterStringStartsWith() As String
            Get
                Return ResourceManager.GetString("FilterStringStartsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contains.
        '''</summary>
        Friend Shared ReadOnly Property FilterStringSubstringOf() As String
            Get
                Return ResourceManager.GetString("FilterStringSubstringOf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drag a column header and drop it here to group by that column.
        '''</summary>
        Friend Shared ReadOnly Property GroupHint() As String
            Get
                Return ResourceManager.GetString("GroupHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert.
        '''</summary>
        Friend Shared ReadOnly Property Insert() As String
            Get
                Return ResourceManager.GetString("Insert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No records to display..
        '''</summary>
        Friend Shared ReadOnly Property NoRecords() As String
            Get
                Return ResourceManager.GetString("NoRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page .
        '''</summary>
        Friend Shared ReadOnly Property Page() As String
            Get
                Return ResourceManager.GetString("Page", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to of {0}.
        '''</summary>
        Friend Shared ReadOnly Property PageOf() As String
            Get
                Return ResourceManager.GetString("PageOf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend Shared ReadOnly Property Refresh() As String
            Get
                Return ResourceManager.GetString("Refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save changes.
        '''</summary>
        Friend Shared ReadOnly Property SaveChanges() As String
            Get
                Return ResourceManager.GetString("SaveChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sorted ascending.
        '''</summary>
        Friend Shared ReadOnly Property SortedAsc() As String
            Get
                Return ResourceManager.GetString("SortedAsc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sorted descending.
        '''</summary>
        Friend Shared ReadOnly Property SortedDesc() As String
            Get
                Return ResourceManager.GetString("SortedDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ungroup.
        '''</summary>
        Friend Shared ReadOnly Property UnGroup() As String
            Get
                Return ResourceManager.GetString("UnGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update.
        '''</summary>
        Friend Shared ReadOnly Property Update() As String
            Get
                Return ResourceManager.GetString("Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select.
        '''</summary>
        Friend Shared ReadOnly Property _Select() As String
            Get
                Return ResourceManager.GetString("Select", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
