//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 3/19/2010 4:48:09 PM
namespace IQWorksTelerikCodeLib.Models
{
    
    /// <summary>
    /// There are no comments for iqDataEntities in the schema.
    /// </summary>
    public partial class iqDataEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new iqDataEntities object using the connection string found in the 'iqDataEntities' section of the application configuration file.
        /// </summary>
        public iqDataEntities() : 
                base("name=iqDataEntities", "iqDataEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new iqDataEntities object.
        /// </summary>
        public iqDataEntities(string connectionString) : 
                base(connectionString, "iqDataEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new iqDataEntities object.
        /// </summary>
        public iqDataEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "iqDataEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for iqCompany in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<iqCompany> iqCompany
        {
            get
            {
                if ((this._iqCompany == null))
                {
                    this._iqCompany = base.CreateQuery<iqCompany>("[iqCompany]");
                }
                return this._iqCompany;
            }
        }
        private global::System.Data.Objects.ObjectQuery<iqCompany> _iqCompany;
        /// <summary>
        /// There are no comments for iqCompany in the schema.
        /// </summary>
        public void AddToiqCompany(iqCompany iqCompany)
        {
            base.AddObject("iqCompany", iqCompany);
        }
    }
    /// <summary>
    /// There are no comments for iqDataModel.iqCompany in the schema.
    /// </summary>
    /// <KeyProperties>
    /// coCompanyNo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="iqDataModel", Name="iqCompany")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class iqCompany : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new iqCompany object.
        /// </summary>
        /// <param name="coCompanyNo">Initial value of coCompanyNo.</param>
        /// <param name="coCompanyName">Initial value of coCompanyName.</param>
        /// <param name="coAddress1">Initial value of coAddress1.</param>
        /// <param name="coAddress2">Initial value of coAddress2.</param>
        /// <param name="coCity">Initial value of coCity.</param>
        /// <param name="coProvince">Initial value of coProvince.</param>
        /// <param name="coPostalCode">Initial value of coPostalCode.</param>
        /// <param name="coPhone">Initial value of coPhone.</param>
        /// <param name="coContact">Initial value of coContact.</param>
        /// <param name="coEmail">Initial value of coEmail.</param>
        /// <param name="coGroupCode">Initial value of coGroupCode.</param>
        /// <param name="coCreatedBy">Initial value of coCreatedBy.</param>
        /// <param name="coUpdatedBy">Initial value of coUpdatedBy.</param>
        /// <param name="coSubscriberNo">Initial value of coSubscriberNo.</param>
        /// <param name="coDateCreated">Initial value of coDateCreated.</param>
        /// <param name="coDateUpdated">Initial value of coDateUpdated.</param>
        public static iqCompany CreateiqCompany(
                    int coCompanyNo, 
                    string coCompanyName, 
                    string coAddress1, 
                    string coAddress2, 
                    string coCity, 
                    string coProvince, 
                    string coPostalCode, 
                    string coPhone, 
                    string coContact, 
                    string coEmail, 
                    string coGroupCode, 
                    int coCreatedBy, 
                    int coUpdatedBy, 
                    int coSubscriberNo, 
                    global::System.DateTime coDateCreated, 
                    global::System.DateTime coDateUpdated)
        {
            iqCompany iqCompany = new iqCompany();
            iqCompany.coCompanyNo = coCompanyNo;
            iqCompany.coCompanyName = coCompanyName;
            iqCompany.coAddress1 = coAddress1;
            iqCompany.coAddress2 = coAddress2;
            iqCompany.coCity = coCity;
            iqCompany.coProvince = coProvince;
            iqCompany.coPostalCode = coPostalCode;
            iqCompany.coPhone = coPhone;
            iqCompany.coContact = coContact;
            iqCompany.coEmail = coEmail;
            iqCompany.coGroupCode = coGroupCode;
            iqCompany.coCreatedBy = coCreatedBy;
            iqCompany.coUpdatedBy = coUpdatedBy;
            iqCompany.coSubscriberNo = coSubscriberNo;
            iqCompany.coDateCreated = coDateCreated;
            iqCompany.coDateUpdated = coDateUpdated;
            return iqCompany;
        }
        /// <summary>
        /// There are no comments for Property coCompanyNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int coCompanyNo
        {
            get
            {
                return this._coCompanyNo;
            }
            set
            {
                this.OncoCompanyNoChanging(value);
                this.ReportPropertyChanging("coCompanyNo");
                this._coCompanyNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coCompanyNo");
                this.OncoCompanyNoChanged();
            }
        }
        private int _coCompanyNo;
        partial void OncoCompanyNoChanging(int value);
        partial void OncoCompanyNoChanged();
        /// <summary>
        /// There are no comments for Property coCompanyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coCompanyName
        {
            get
            {
                return this._coCompanyName;
            }
            set
            {
                this.OncoCompanyNameChanging(value);
                this.ReportPropertyChanging("coCompanyName");
                this._coCompanyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coCompanyName");
                this.OncoCompanyNameChanged();
            }
        }
        private string _coCompanyName;
        partial void OncoCompanyNameChanging(string value);
        partial void OncoCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property coAddress1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coAddress1
        {
            get
            {
                return this._coAddress1;
            }
            set
            {
                this.OncoAddress1Changing(value);
                this.ReportPropertyChanging("coAddress1");
                this._coAddress1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coAddress1");
                this.OncoAddress1Changed();
            }
        }
        private string _coAddress1;
        partial void OncoAddress1Changing(string value);
        partial void OncoAddress1Changed();
        /// <summary>
        /// There are no comments for Property coAddress2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coAddress2
        {
            get
            {
                return this._coAddress2;
            }
            set
            {
                this.OncoAddress2Changing(value);
                this.ReportPropertyChanging("coAddress2");
                this._coAddress2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coAddress2");
                this.OncoAddress2Changed();
            }
        }
        private string _coAddress2;
        partial void OncoAddress2Changing(string value);
        partial void OncoAddress2Changed();
        /// <summary>
        /// There are no comments for Property coCity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coCity
        {
            get
            {
                return this._coCity;
            }
            set
            {
                this.OncoCityChanging(value);
                this.ReportPropertyChanging("coCity");
                this._coCity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coCity");
                this.OncoCityChanged();
            }
        }
        private string _coCity;
        partial void OncoCityChanging(string value);
        partial void OncoCityChanged();
        /// <summary>
        /// There are no comments for Property coProvince in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coProvince
        {
            get
            {
                return this._coProvince;
            }
            set
            {
                this.OncoProvinceChanging(value);
                this.ReportPropertyChanging("coProvince");
                this._coProvince = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coProvince");
                this.OncoProvinceChanged();
            }
        }
        private string _coProvince;
        partial void OncoProvinceChanging(string value);
        partial void OncoProvinceChanged();
        /// <summary>
        /// There are no comments for Property coPostalCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coPostalCode
        {
            get
            {
                return this._coPostalCode;
            }
            set
            {
                this.OncoPostalCodeChanging(value);
                this.ReportPropertyChanging("coPostalCode");
                this._coPostalCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coPostalCode");
                this.OncoPostalCodeChanged();
            }
        }
        private string _coPostalCode;
        partial void OncoPostalCodeChanging(string value);
        partial void OncoPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property coPhone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coPhone
        {
            get
            {
                return this._coPhone;
            }
            set
            {
                this.OncoPhoneChanging(value);
                this.ReportPropertyChanging("coPhone");
                this._coPhone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coPhone");
                this.OncoPhoneChanged();
            }
        }
        private string _coPhone;
        partial void OncoPhoneChanging(string value);
        partial void OncoPhoneChanged();
        /// <summary>
        /// There are no comments for Property coContact in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coContact
        {
            get
            {
                return this._coContact;
            }
            set
            {
                this.OncoContactChanging(value);
                this.ReportPropertyChanging("coContact");
                this._coContact = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coContact");
                this.OncoContactChanged();
            }
        }
        private string _coContact;
        partial void OncoContactChanging(string value);
        partial void OncoContactChanged();
        /// <summary>
        /// There are no comments for Property coEmail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coEmail
        {
            get
            {
                return this._coEmail;
            }
            set
            {
                this.OncoEmailChanging(value);
                this.ReportPropertyChanging("coEmail");
                this._coEmail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coEmail");
                this.OncoEmailChanged();
            }
        }
        private string _coEmail;
        partial void OncoEmailChanging(string value);
        partial void OncoEmailChanged();
        /// <summary>
        /// There are no comments for Property coGroupCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string coGroupCode
        {
            get
            {
                return this._coGroupCode;
            }
            set
            {
                this.OncoGroupCodeChanging(value);
                this.ReportPropertyChanging("coGroupCode");
                this._coGroupCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("coGroupCode");
                this.OncoGroupCodeChanged();
            }
        }
        private string _coGroupCode;
        partial void OncoGroupCodeChanging(string value);
        partial void OncoGroupCodeChanged();
        /// <summary>
        /// There are no comments for Property coCreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int coCreatedBy
        {
            get
            {
                return this._coCreatedBy;
            }
            set
            {
                this.OncoCreatedByChanging(value);
                this.ReportPropertyChanging("coCreatedBy");
                this._coCreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coCreatedBy");
                this.OncoCreatedByChanged();
            }
        }
        private int _coCreatedBy;
        partial void OncoCreatedByChanging(int value);
        partial void OncoCreatedByChanged();
        /// <summary>
        /// There are no comments for Property coUpdatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int coUpdatedBy
        {
            get
            {
                return this._coUpdatedBy;
            }
            set
            {
                this.OncoUpdatedByChanging(value);
                this.ReportPropertyChanging("coUpdatedBy");
                this._coUpdatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coUpdatedBy");
                this.OncoUpdatedByChanged();
            }
        }
        private int _coUpdatedBy;
        partial void OncoUpdatedByChanging(int value);
        partial void OncoUpdatedByChanged();
        /// <summary>
        /// There are no comments for Property coSubscriberNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int coSubscriberNo
        {
            get
            {
                return this._coSubscriberNo;
            }
            set
            {
                this.OncoSubscriberNoChanging(value);
                this.ReportPropertyChanging("coSubscriberNo");
                this._coSubscriberNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coSubscriberNo");
                this.OncoSubscriberNoChanged();
            }
        }
        private int _coSubscriberNo;
        partial void OncoSubscriberNoChanging(int value);
        partial void OncoSubscriberNoChanged();
        /// <summary>
        /// There are no comments for Property coDateCreated in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime coDateCreated
        {
            get
            {
                return this._coDateCreated;
            }
            set
            {
                this.OncoDateCreatedChanging(value);
                this.ReportPropertyChanging("coDateCreated");
                this._coDateCreated = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coDateCreated");
                this.OncoDateCreatedChanged();
            }
        }
        private global::System.DateTime _coDateCreated;
        partial void OncoDateCreatedChanging(global::System.DateTime value);
        partial void OncoDateCreatedChanged();
        /// <summary>
        /// There are no comments for Property coDateUpdated in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime coDateUpdated
        {
            get
            {
                return this._coDateUpdated;
            }
            set
            {
                this.OncoDateUpdatedChanging(value);
                this.ReportPropertyChanging("coDateUpdated");
                this._coDateUpdated = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("coDateUpdated");
                this.OncoDateUpdatedChanged();
            }
        }
        private global::System.DateTime _coDateUpdated;
        partial void OncoDateUpdatedChanging(global::System.DateTime value);
        partial void OncoDateUpdatedChanged();
    }
}
