//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IqResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IqResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IqResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string coAddress1 {
            get {
                return ResourceManager.GetString("coAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string coAddress2 {
            get {
                return ResourceManager.GetString("coAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string coCity {
            get {
                return ResourceManager.GetString("coCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string coCompanyName {
            get {
                return ResourceManager.GetString("coCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Number.
        /// </summary>
        internal static string coCompanyNo {
            get {
                return ResourceManager.GetString("coCompanyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string coContact {
            get {
                return ResourceManager.GetString("coContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string coCreatedBy {
            get {
                return ResourceManager.GetString("coCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string coDateCreated {
            get {
                return ResourceManager.GetString("coDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Updated.
        /// </summary>
        internal static string coDateUpdated {
            get {
                return ResourceManager.GetString("coDateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string coEmail {
            get {
                return ResourceManager.GetString("coEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code.
        /// </summary>
        internal static string coGroupCode {
            get {
                return ResourceManager.GetString("coGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string coPhone {
            get {
                return ResourceManager.GetString("coPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string coPostalCode {
            get {
                return ResourceManager.GetString("coPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string coProvince {
            get {
                return ResourceManager.GetString("coProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber Number.
        /// </summary>
        internal static string coSubscriberNo {
            get {
                return ResourceManager.GetString("coSubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string coUpdatedBy {
            get {
                return ResourceManager.GetString("coUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p class=&quot;iqParagraph&quot;&gt;This is our small contribution to the Telerik Code Library and the Telerik community &lt;/p&gt;
        ///
        ///&lt;p  class=&quot;iqParagraph&quot;&gt; We use Telerik MVC controls because they offer hundreds of different ways to code the UI and enhance the interactive user experience.&lt;/p&gt;
        ///
        ///&lt;p  class=&quot;iqParagraph&quot;&gt; I get many benefits from seeing how others code and  use Telerik control properties, javascript, jQuery and CSS with Telerik controls. What helps alot is to see concrete examples of how these ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string greetHome {
            get {
                return ResourceManager.GetString("greetHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Even though tooltips are easy to do, there are many ways to code them. This is just another technique we wanted to try. 
        ///&lt;A href=&quot;http://iqworkswp.wordpress.com/&quot;&gt;Visit our IQWorks Telerik MVC Tooltip Blog !&lt;/A&gt;.&lt;br&gt;
        ///&lt;/p&gt;.
        /// </summary>
        internal static string greetTooltips {
            get {
                return ResourceManager.GetString("greetTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Std_About {
            get {
                return ResourceManager.GetString("Std_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Hi  &lt;/p&gt;
        ///
        /// &lt;p&gt;  My name is David C. Simmons. &lt;/p&gt; 
        ///
        /// &lt;p&gt;  I am the lead .NET web application developer at Information Quality Works. &lt;/p&gt;       
        ///&lt;p&gt;   IQWorks has been around for over 15 years. &lt;/p&gt; 
        ///
        ///&lt;p&gt;   We started out as an IBM/AS400 consulting group, and like many others, included web development in the mid 90&apos;s.         
        /// &lt;p&gt;   Our primary focus is on exercise and fitness web application 
        ///development.  However, we do provide standard business web application development and consulting and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Std_AboutVerbiage {
            get {
                return ResourceManager.GetString("Std_AboutVerbiage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Std_Close {
            get {
                return ResourceManager.GetString("Std_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Examples &gt;.
        /// </summary>
        internal static string Std_CurrentSamples {
            get {
                return ResourceManager.GetString("Std_CurrentSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Std_Home {
            get {
                return ResourceManager.GetString("Std_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Quality Works.
        /// </summary>
        internal static string Std_InformationQualityWorks {
            get {
                return ResourceManager.GetString("Std_InformationQualityWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Select the tooltip scenerio you would like to see. .
        /// </summary>
        internal static string Std_Instructions {
            get {
                return ResourceManager.GetString("Std_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;br&gt;
        /// 
        ///Revision History: &lt;br&gt;&lt;br&gt;
        ///01.01.01 * 03/24/2010 -&lt;br&gt; 
        ///1 - Initial Version. &lt;br&gt;&lt;br&gt;
        ///
        ///01.01.02 * 03/25/2010 - &lt;br&gt;
        ///1 -  
        ///&lt;A href=&quot;http://dotnetslackers.com/JavaScript/re-260035_Rich_Tooltips_With_jQuery.aspx&quot;&gt;Acknowledgement to Scott Mitchell for his tooltip inspiration !&lt;/A&gt;.&lt;br&gt; 
        ///2 - Deleted uneeded ascx file.&lt;br&gt;&lt;br&gt;
        ///01.01.03 * 03/25/2010 - &lt;br&gt;
        ///1 - Intermittent error in Fire fox after clicking the browser toolbar Reload and then clicking tabs to reloading grids. Currently 
        ///being  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Std_Revisions {
            get {
                return ResourceManager.GetString("Std_Revisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telerik Code Lib Contribution - MVC1 2010.1.309.
        /// </summary>
        internal static string Std_TelerikCodeLibContribution {
            get {
                return ResourceManager.GetString("Std_TelerikCodeLibContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool tip from data.
        /// </summary>
        internal static string Std_TooltipFromData {
            get {
                return ResourceManager.GetString("Std_TooltipFromData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;   &lt;p&gt;    Here are a few points of interest about this script, and some things I encountered during this project. &lt;/p&gt;     
        ///
        /// &lt;p&gt; 1 - Regular hover didn&apos;t seem to work with ajax here because if you page forward, the next page will not pick up the hover. So, I tried to use .live with hover.&lt;/p&gt;   
        ///
        /// &lt;p&gt; 2 - &lt;a href=&quot;http://api.jquery.com/live/&quot;&gt;JQuery&apos;s .live&lt;/a&gt; doesn&apos;t seem to work well here with &quot;hover&quot;. The tooltip will stick and not get removed with standard hover (handleIn/handleOut) coding. &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Std_TooltipFromDataDoc {
            get {
                return ResourceManager.GetString("Std_TooltipFromDataDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; 1 - Regular hover dosnt work with ajax here. If you page forward
        ///            ,the next page will not pick up the hover. So, we use .live&lt;/p&gt; 
        ///       &lt;p&gt;  2 - .live dosnt work with &quot;hover&quot;. The tooltip will stick and not 
        ///            get removed with standard hover coding. &lt;/p&gt; 
        ///       &lt;p&gt;  3 - .live works with mouseover and mouseout.&lt;/p&gt; 
        ///       &lt;p&gt;  4 - I use the variable &quot;thisi&quot; so that &quot;this&quot; can be accessed inside
        ///            the getJSON function &lt;/p&gt; 
        ///      &lt;p&gt;   5 - Included the main toolti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Std_TooltipFromDataNotes {
            get {
                return ResourceManager.GetString("Std_TooltipFromDataNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip from Grid.
        /// </summary>
        internal static string Std_TooltipFromGrid {
            get {
                return ResourceManager.GetString("Std_TooltipFromGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Here is some documentation for TooltipOverColumn.ascx.&lt;/p&gt;
        ///  
        ///     &lt;p&gt;1 - Regular hover dosen&apos;t seem to work with ajax here because if you page forward
        ///     ,the next page will not pick up the hover. , we tried to use .live with hover. &lt;/p&gt;
        ///
        ///     &lt;p&gt;2 - .live dosnt work well with &quot;hover&quot;. The tooltip will stick and not 
        ///     get removed with standard hover (handleIn/handleOut) coding. &lt;/p&gt;
        /// 
        ///    &lt;p&gt; 3 - .live works with mouseover/mouseout  
        ///     Mouseenter/leave fires more directly 
        ///     on th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Std_TooltipOverColumnDoc {
            get {
                return ResourceManager.GetString("Std_TooltipOverColumnDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tootip Over Columns.
        /// </summary>
        internal static string Std_TooltipOverColumns {
            get {
                return ResourceManager.GetString("Std_TooltipOverColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips.
        /// </summary>
        internal static string Std_Tooltips {
            get {
                return ResourceManager.GetString("Std_Tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Samples.
        /// </summary>
        internal static string Std_TooltipSamples {
            get {
                return ResourceManager.GetString("Std_TooltipSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips.
        /// </summary>
        internal static string Std_Toottips {
            get {
                return ResourceManager.GetString("Std_Toottips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQWorks Version 01.01.05.
        /// </summary>
        internal static string Std_Version {
            get {
                return ResourceManager.GetString("Std_Version", resourceCulture);
            }
        }
    }
}
